/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INICIO = 1;
  /** RegularExpression Id. */
  int LLAVEIZQ = 2;
  /** RegularExpression Id. */
  int LLAVEDER = 3;
  /** RegularExpression Id. */
  int PARENTEIZQ = 4;
  /** RegularExpression Id. */
  int PARENTEDER = 5;
  /** RegularExpression Id. */
  int COMA = 6;
  /** RegularExpression Id. */
  int NEGACION = 7;
  /** RegularExpression Id. */
  int CONSTANTE = 8;
  /** RegularExpression Id. */
  int LETRAPREDICADO = 9;
  /** RegularExpression Id. */
  int LETRAVARIABLE = 10;
  /** RegularExpression Id. */
  int LETRAFUNCION = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"S=\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"~\"",
    "<CONSTANTE>",
    "<LETRAPREDICADO>",
    "<LETRAVARIABLE>",
    "<LETRAFUNCION>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\\n\"",
  };

}
